"""add 3 column to Blog,1 column to comment and 1 column to rate

Revision ID: 786b907c23da
Revises: 
Create Date: 2024-12-20 18:16:32.545311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786b907c23da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_comments', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coment', sa.String(), nullable=False))

    with op.batch_alter_table('rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate', schema=None) as batch_op:
        batch_op.drop_column('rate')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('coment')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('total_comments')
        batch_op.drop_column('total_likes')

    # ### end Alembic commands ###
